services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://api.nccppl.com
        VITE_API_PATH_PREFIX: ""
        VITE_MSG91_WIDGET_ID: ${VITE_MSG91_WIDGET_ID:-}
        VITE_MSG91_WIDGET_AUTH_TOKEN: ${VITE_MSG91_WIDGET_AUTH_TOKEN:-}
    container_name: nyra_admin
    ports:
      - "8081:80"
    restart: unless-stopped

  admin_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://api-dev.nccppl.com
        VITE_API_PATH_PREFIX: ""
        VITE_MSG91_WIDGET_ID: ${VITE_MSG91_WIDGET_ID:-}
        VITE_MSG91_WIDGET_AUTH_TOKEN: ${VITE_MSG91_WIDGET_AUTH_TOKEN:-}
    container_name: nyra_admin_dev
    ports:
      - "8084:80"
    restart: unless-stopped
